export const Socios = [
    {
        "nombre": 'Juan',
        "apellido": 'Perez',
        "dni": 40147963,
        "direccion": 'Av. Libertador 123',
        "telefono": 1122334455,
        "foto": 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmFuZG9tJTIwcGVvcGxlfGVufDB8fDB8fHww',
        "usuario": 'juanperez@gmail.com',
        "contraseña": 'juanperez963',
        "cuotas": [
            {
                "concepto": 'Cuota 1',
                "mes": '1',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/01/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 2',
                "mes": '2',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/02/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 3',
                "mes": '3',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/03/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 4',
                "mes": '4',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/04/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 5',
                "mes": '5',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/05/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 6',
                "mes": '6',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/06/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 7',
                "mes": '7',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/07/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 8',
                "mes": '8',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/08/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 9',
                "mes": '9',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/09/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 10',
                "mes": '10',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/10/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 11',
                "mes": '11',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/11/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            },
            {
                "concepto": 'Cuota 12',
                "mes": '12',
                "año": '2023',
                "valor": "$2000",
                "fecha": '15/12/2023',
                "pagado": 0,
                "fechaPago": '',
                "estado": 'pendiente',
            }
        ],
        "reservas": [{
            "lugar": "Cancha",
            "fecha": "2023-11-11",
            "hora": "19:00",
            "estado": "Reservado"
        }],
        "estado": '',
        "fechaActivo": '15/01/2021'
    },
    {
        "nombre": "María",
        "apellido": "García",
        "dni": 87654321,
        "direccion": "Calle Mayor 456",
        "telefono": 5544332211,
        "foto": "https://images.unsplash.com/photo-1504711434967-e82da70b1d92?auto=format&fit=crop&w=500&h=350&q=60",
        "usuario": "mariagarcia@gmail.com",
        "contraseña": "mariagarcia876",
        "cuotas": [
            
        ],
        "reservas": [],
        "estado": "activo",
        "fechaActivo": "20/03/2021"
    },
    {
        "nombre": "Luis",
        "apellido": "Martínez",
        "dni": 19283746,
        "direccion": "Avenida 123",
        "telefono": 6677889900,
        "foto": "https://images.unsplash.com/photo-1532589413292-2817f35e64c9?auto=format&fit=crop&w=500&q=60",
        "usuario": "luismtz@gmail.com",
        "contraseña": "luismartinez123",
        "cuotas": [
            // ... cuotas de Luis
        ],
        "reservas": [],
        "estado": "activo",
        "fechaActivo": "10/05/2021"
    },
    {
        "nombre": "Ana",
        "apellido": "López",
        "dni": 56473829,
        "direccion": "Rue de la Paix 789",
        "telefono": 3355778899,
        "foto": "https://images.unsplash.com/photo-1511629097353-cc5eb3fe46e1?auto=format&fit=crop&w=500&q=60",
        "usuario": "anita.lopez@gmail.com",
        "contraseña": "anitaL789",
        "cuotas": [
            // ... cuotas de Ana
        ],
        "reservas": [],
        "estado": "activo",
        "fechaActivo": "05/02/2021"
    },
    {
        "nombre": "Carlos",
        "apellido": "Sánchez",
        "dni": 97531028,
        "direccion": "Baker Street 221B",
        "telefono": 1122334455,
        "foto": "https://images.unsplash.com/photo-1494947665470-20322015e3fd?auto=format&fit=crop&w=500&q=60",
        "usuario": "carlossanchez@gmail.com",
        "contraseña": "carlossanchez28",
        "cuotas": [
            // ... cuotas de Carlos
        ],
        "reservas": [],
        "estado": "activo",
        "fechaActivo": "30/09/2021"
    }
];
